{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "media-god",
  "main": ".open-next/worker.js",
  "compatibility_date": "2026-08-15",
  "assets": {
    "directory": ".open-next/assets",
    "binding": "ASSETS"
  },
  "observability": {
    "enabled": true
  }
}name = "media-god"  compatibility_date = "2026-08-15"  main = ".open-next/worker.js"  [assets]  directory = ".open-next/assets"  binding = "ASSETS"  [observability]  enabled = true 
